# GNC Scraper for the preparedness data on kobo for the ERP dataviz

name: GNC ERP Kobo Data scraper

on:
  schedule:
    - cron: '0 8 * * *' # everyday 0 8 * * MON, every 10 min */10 * * * * -- 0 8 * * *

# permissions: read-all|write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip 
          pip install setuptools
          pip install -r requirements.txt
          
      - name: execute py script # run run.py
        env: 
          GNCERPKOBOID: ${{ secrets.GNCERPKOBOID }}
        run: python run.py
          
      - name: commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data successfully fetched and updated
          push_options: '--force'
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
